### ISSUE TITLE
Multiple commands do not work

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roam42#415]
Looks like commands from `Command Palette Plus` that call `promptPathAndCallback` break.
from [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1686754645333909?thread_ts=1686683277.948409&cid=C016N2B66JU)

- [x] [update roamjs-components](https://github.com/dvargas92495/roamjs-components/pull/6)
- [ ] update workbench roamjs-components version

eg:
- `Open Page in Sidebar (ops)`
- Move Block Commands
- Send Commands
- etc

The dialog shows up
![image](https://github.com/dvargas92495/roamjs-workbench/assets/3792666/15a686c7-2196-4db4-991f-dd4af57c189c)

Then

Console Error
```
instrument.ts:132 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Bg (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:372:1)
    at ff (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:321:126)
    at setValue (FormDialog.tsx:255:21)
    at AutocompleteInput.tsx:110:16
    at Gl (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:396:450)
    at main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:210:257
    at rh (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:279:286)
    at Kk (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:395:380)
    at Jg (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:377:257)
    at main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:280:14
    at main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:210:257
    at rh (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:279:286)
    at gi (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:279:468)
    at Sh (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:279:401)
    at Gl (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:397:143)
    at main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:210:257
    at rh (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:279:286)
    at Kk (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:395:380)
    at main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:395:284
    at h (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:205:79)
    at MessagePort.<anonymous> (main.js?__WB_REVISION__=a483756fb07b148177a1ff2101901681:208:334)
```

**Comment by dvargasfuertes** [comment]
ah this is related to the `AutocompleteInput` changes probable. Remind me tomorrow "on stream" so we could patch it then

**Comment by dvargasfuertes** [comment]
I think this might be due to an older version of `roamjs-components` - I've upgraded the dependency, let's recheck whether or not this is an issue

**Comment by mdroidian** [comment]
As discussed, it looks like the `page` autocomplete is still an issue.
